@startuml Ejercicio 2

skinparam packageStyle rectangle
left to right direction

actor Alumno
actor Profesor

rectangle Aula_Virtual_Moodle {
    (Abrir curso) as (AbrirCur)
    (Administrar curso) as (AdminCur)

    (Escoger materia entre las que este matriculado) as (EsMa)

    (Subir entregas) as (SubEnt)
    (Consultar contenido) as (ConCon)
    (Descargar contenido) as (DesCon)
    (Consultar calificaciones) as (ConCal)

    (Fijar/Modificar entrega) as (Ent)
    (Subir contenidos) as (Sub)
    (Calificar entrega) as (Cal)
    
    (Ver mensaje) as (VerMen)
    (Escribir mensaje) as (EscMen)

    (Eliminar alumno) as (ElAl)
    (Añadir alumno) as (AnAl)
    
    Alumno -- EscMen
    Alumno -- VerMen

    Alumno -- EsMa

    EsMa <.... DesCon : extend
    EsMa <.... ConCon : extend
    EsMa <... SubEnt : extend
    EsMa <... ConCal : extend

    AbrirCur .> AdminCur : includes
    
    Profesor ----- EscMen
    Profesor ----- VerMen
    Profesor ----- AbrirCur
    Profesor ----- AdminCur
    AdminCur <.... Ent : extend
    AdminCur <..... Sub : extend
    AdminCur <.... Cal : extend
    AdminCur <.... AnAl : extend
    AdminCur <.... ElAl : extend
    

    




    
}

@enduml
