@startuml Ejercicio 2

skinparam packageStyle rectangle
left to right direction

actor Alumno
actor Profesor

rectangle Aula_Virtual_Moodle {
    (Abrir curso) as (AbrirCur)
    (Administrar curso) as (AdminCur)

    (Cuenta Alumno) as (CueAlu)
    (Escoger materia entre las que este matriculado) as (EsMa)
    (Cuenta Profesor) as (CuenProf)

    (Subir entregas) as (SubEnt)
    (Consultar contenido) as (ConCon)
    (Descargar contenido) as (DesCon)
    (Consultar calificaciones) as (ConCal)

    (Fijar/Modificar entrega) as (Ent)
    (Subir contenidos) as (Sub)
    (Calificar entrega) as (Cal)
    
    (Ver mensaje) as (VerMen)
    (Escribir mensaje) as (EscMen)

    (Eliminar alumno) as (ElAl)
    (Añadir alumno) as (AnAl)
    
    Profesor -up- CuenProf
    Alumno -- CueAlu

    CueAlu <.. EsMa : extends

    EsMa <.... DesCon : extends
    EsMa <.... ConCon : extends
    EsMa <... SubEnt : extends
    EsMa <... ConCal : extends
    CueAlu <... EscMen : extends
    CueAlu <... VerMen : extends

    AbrirCur .> AdminCur : includes
    

    CuenProf <.... EscMen : extends
    CuenProf <.... VerMen : extends
    CuenProf <.... AbrirCur : extends
    AdminCur <..... Ent : extends
    AdminCur <..... Sub : extends
    AdminCur <.... Cal : extends
    AdminCur <.... AnAl : extends
    AdminCur <.... ElAl : extends
    

    




    
}

@enduml
