@startuml Ejercicio 1

skinparam packageStyle rectangle
left to right direction

actor Socios

actor Fabrica

actor Cliente

rectangle  Sistema_de_Ventas_de_la_Empresa {
(Compra producto) as (Comprar)
(Comprar en la fabrica) as (CompFab)
(Comprar por Internet) as (CompInt)
(Comprar en la tienda) as (CompTie)
(Venta en fabrica) as (VenFab)
(Venta por Internet) as (VenInt)
(Venta en tienda) as (VenTien)
(Venta a otro socio) as (VenSoc)
(Recogen beneficios) as (Benef)
(Elabora productos) as (Productos)
(Retirar productos) as (Recoger)
(Venta a un precio mayor o igual al de la fábrica) as (VentaNormal)
(Venta en lotes del stock no deseado) as (Lotes)



Fabrica ----  Productos
Productos <.... VenInt : extend
Productos <.... VenFab : extend

Productos <.. Recoger : extend

Recoger ------ Socios

Socios ----- VenSoc
Socios -- VenTien

VenTien <.... VentaNormal : extend
VenTien <.... Lotes : extend

Cliente ---- Comprar
Comprar <.... CompTie: extend
Comprar <.... CompFab : extend
Comprar <.... CompInt : extend
VenFab ..> Benef : include
VenInt ..> Benef : include


}

@enduml